run:
  # wandb_project: false
  wandb_tags: ["owt", "leaderboard"]

data:
  train_data_path: "/data/c-sniderb/tokens/owt-train/tokens.bin"
  valid_data_path: "/data/c-sniderb/tokens/owt-valid/tokens.bin"

model:
  d_model: 896
  d_ff: 2368
  # d_ff: 4096
  num_heads: 14
  num_layers: 12
  context_length: 512
  vocab_size: 32_000
  weight_tying: true
  ffn_type: "swiglu"
  # ffn_type: "silu"
  attn_impl: "normal" 

optimizer:
  lr: 1.4e-3
  betas: [0.9, 0.98]
  eps: 1.0e-8
  weight_decay: 0.01

# Total tokens = batch_size * max_steps * context_length
# 128 * 17_500 * 512 = 1,120,000,000 = 1.120B
# Required throughput = 1.120B tokens / 5400s = 207k tokens/s
# Current empirical throughput: 220k tokens/s (max. 1,188,000,000 = 1.188B total)

training:
  batch_size: 128
  max_steps: 17_500
  eval_interval: 1750
  eval_steps: 30
  eval_batch_size: 128
  checkpoint_interval: 17_500
  max_l2_norm: 1.0
  lr_max: 1.4e-3
  lr_min: 4.0e-4
  warmup_ratio: 0.03
  # cosine_cycle_iters: 42_000 # hack to change shape of cosine schedule